### ISSUE TITLE
Update Travis build matrix

### ISSUE THREAD

**Issue by sestrella** [stackbuilders/cassava-megaparsec#14]
It looks like we are not building this library against recent versions of GHC such as 8.8 and 8.10:

https://github.com/stackbuilders/cassava-megaparsec/blob/7ebe5f2846fa571b8d82d270257001fe12b81088/.travis.yml#L12-L21

On the other hand, maybe it is about time to [Stop supporting older GHCs](https://www.snoyman.com/blog/2018/07/stop-supporting-older-ghcs)

**Comment by CristhianMotoche** [comment]
Hi @sestrella Which versions should we stop supporting? My guess is that we should stop supporting version `< 8.X`.

**Comment by CristhianMotoche** [comment]
Hey @sestrella I think we should migrate to use GH actions as we do it for other haskell projects. WDYT?

**Comment by cptrodolfox** [comment]
@CristhianMotoche I have created the following PR https://github.com/stackbuilders/cassava-megaparsec/pull/25 for adding github actions. I will be closing this issue.
