### ISSUE TITLE
cassava-megaparsec-2.0.4 fails to build with GHC 7.10 and 8.2

### ISSUE THREAD

**Issue by andreasabel** [stackbuilders/cassava-megaparsec#26]
`cassava-megaparsec-2.0.4` fails to build with GHC 7.10 and 8.2, due to shortcomings of these compilers:
```
Building library for cassava-megaparsec-2.0.4..
[2 of 2] Compiling Data.Csv.Parser.Megaparsec ( Data/Csv/Parser/Megaparsec.hs, /Users/abel/tmp/cassava-megaparsec-2.0.4/dist-newstyle/build/x86_64-osx/ghc-7.10.3/cassava-megaparsec-2.0.4/build/Data/Csv/Parser/Megaparsec.o )
ghc: panic! (the 'impossible' happened)
  (GHC version 7.10.3 for x86_64-apple-darwin):
	Simplifier ticks exhausted
  When trying UnfoldingDone $fAlternativeParsecT_$cmappend
  To increase the limit, use -fsimpl-tick-factor=N (default 100)
  If you need to do this, let GHC HQ know, and what factor you needed
  To see detailed counts use -ddump-simpl-stats
  Total ticks: 5523
```
(similar message for GHC 8.0.2).

Build with GHC 8.2 - 9.4 works fine, according to my experiments.  In a Hackage revision, I indicated the build situation by up-dating the field `tested-with`: https://hackage.haskell.org/package/cassava-megaparsec-2.0.4/revisions/

Not sure how to further proceed:
- Pass extra flags to GHC to fix the problem?
- Drop GHC 7.10 and 8.0 completely by setting `base >= 4.10`?

Note that the problem also exists on `master`:
- https://github.com/stackbuilders/cassava-megaparsec/actions/runs/3768436408/jobs/6406931495#step:6:252

**Comment by cptrodolfox** [comment]
Dropped support of GHC <= 8.0

**Comment by andreasabel** [comment]
@cptrodolfox wrote:
> Dropped support of GHC <= 8.0

Should `base >= 4.10` also be manifested in the 2.0.4 release (via a revision on hackage)?
