### ISSUE TITLE
Conflicting type signatures between `cassava` and `cassava-megaparsec`

### ISSUE THREAD

**Issue by dmvianna** [stackbuilders/cassava-megaparsec#3]
I hope I'm not using a hopelessly old release of `cassava` (0.4.5.1), but the type signature of one exported function in it is

```haskell
decodeByName
  :: FromNamedRecord a
  => ByteString
  -> Either String (Header, Vector a)
```

against `cassava-megaparsec` (0.1.0)

```haskell
decodeByName
  :: FromNamedRecord a
  => FilePath
  -> ByteString
  -> Either (Text.Megaparsec.Error.ParseError Char Data.Csv.Parser.Megaparsec.Cec) (Header, Vector a)
```

What is `FilePath` doing there? Some documentation on how to use it would help.

**Comment by mrkkrp** [comment]
The argument just affects parse error messages (the file name is displayed there). I'll add a note about this to the docs.

**Comment by mrkkrp** [comment]
Done.
